### ISSUE TITLE
Is this plugin still working? 

### ISSUE THREAD

**Issue by samuells** [DominikAngerer/localized-story-loader#4]
I found it inside storblok plugins, but as I try to it - the whole app crash.

**Comment by DominikAngerer** [comment]
Hey there! Sorry for the late response. You can now use the built in "Multi Option" and "Single Option". Simply select "Stories" as source & you're ready to go! :) I'll archive this project, since the new plugin system introduced a sandbox solution + another way to access the content delivery API (a way easier one). https://www.storyblok.com/docs/Guides/Creating-a-field-type-plugin

![IMAGE](https://a.storyblok.com/f/46030/335x743/3799272dbd/unbenannt.PNG)

Thanks for the report - I've also removed the reference there 👍 so nobody will be crashing their app. :)


## How would that plugin look with the new plugin sandbox?

Another quick thing for you - a quick rewrite of that plugin (single option tho) would look like the code below. If you want to have a context (language specific) configuration you can load the current story by using the available `storyId` to load it via the API and check for the `full_slug`, parse that accordingly and do your other requests (as done below) using `starts_with`. I would now use the built-in field types and Source "Stories" since it is the more stable option to go 👍 throught of sharing the basic "setup" of that plugin - didn't want to close that issue without any hint on how that could look like now :)

```javascript
const Fieldtype = {
  mixins: [window.Storyblok.plugin],
  template: `<div>
      <select class="uk-width-1-1" v-model="model.value">
        <option v-for="loadedStory in loadedStories" v-bind:value="loadedStory.uuid">{{ loadedStory.name }}</option>
      </select>
    </div>`,
  data() {
    return {
      loadedStories: [],
      contextStory: null
    }
  },
  methods: {
    initWith() {
      return {
        plugin: 'mynewplugintest', // change this to your plugin name
        value: '' // this will be the saved value - I would suggest to save the uuid of the selected story
      }
    },
    pluginCreated() {
      // load current story for context
      this.api.get(`cdn/stories`, { by_ids: this.storyId, version: 'draft'})
      .then((res) => {
        this.contextStory = res.data.stories[0]

        // first to characters -> 'en', 'de', ... and so on is our locale
        let locale = this.contextStory.full_slug.slice(0, 2) 

        // our context now has to start with whatever the locale above is and a / so a content structure like:
        // en/articles
        // de/articles
        // can be loaded.
        this.api.get(`cdn/stories`, { version: 'draft', starts_with: `${locale}/` })
        .then((res) => {
          this.loadedStories = res.data.stories
        })
      })
    }
  },
  watch: {
    'model': {
      handler: function (value) {
        this.$emit('changed-model', value);
      },
      deep: true
    }
  }
}
```

**Comment by samuells** [comment]
Great Thx!
